/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.List;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        printGrammar();

        Scanner scanner = new Scanner(System.in);

        System.out.println("\nВведите арифметическое выражение:");
        if (!scanner.hasNextLine()) {
            System.out.println("Ввод не получен.");
            return;
        }

        String expression = scanner.nextLine();

        try {
            Lexer lexer = new Lexer(expression);
            List<Token> tokens = lexer.tokenize();

            Parser parser = new Parser(tokens);
            Node tree = parser.parseS();

            System.out.println("\n=== Дерево разбора ===");
            tree.printTree();

        } catch (RuntimeException e) {
            System.out.println("\n" + e.getMessage());
        }
    }

    private static void printGrammar() {
        System.out.println("========================================");
        System.out.println("     СИНТАКСИЧЕСКИЙ АНАЛИЗАТОР");
        System.out.println("========================================");

        System.out.println("\nОписание:");
        System.out.println(
                "Программа выполняет лексический и синтаксический анализ "
                        + "арифметических выражений."
        );
        System.out.println(
                "Лексер выделяет числа, идентификаторы и знаки операций, "
                        + "а парсер проверяет соответствие выражения грамматике "
                        + "и строит дерево разбора."
        );

        System.out.println("\nГрамматика:");

        System.out.println("S  -> E");
        System.out.println("E  -> T E'");
        System.out.println("E' -> + T E' | - T E' | ε");
        System.out.println("T  -> F T'");
        System.out.println("T' -> * F T' | / F T' | ε");
        System.out.println("F  -> ( E ) | number | id");

        System.out.println("\nОбозначения:");
        System.out.println("S      — начальный символ грамматики");
        System.out.println("E      — выражение");
        System.out.println("E'     — продолжение выражения (+ или -)");
        System.out.println("T      — терм");
        System.out.println("T'     — продолжение терма (* или /)");
        System.out.println("F      — множитель: число, идентификатор или выражение в скобках");
        System.out.println("number — целое число");
        System.out.println("id     — идентификатор, например x или value_1");
        System.out.println("ε      — пустая последовательность");

        System.out.println("\nПриоритет операций:");
        System.out.println("1. Скобки");
        System.out.println("2. Умножение и деление");
        System.out.println("3. Сложение и вычитание");

        System.out.println("\n========================================");
    }
}