image: registry.csc.sibsutis.ru/ci/git-clang-format:latest
stages:
  - check-format
  - build
  - test

check-format:
  stage: check-format
  script:
    - find . -type f -name '*.[ch]' | xargs clang-format --style=GNU -i
    - find . -type f -name '*.[ch]' | xargs sed -i -e '$a\'


build:
  stage: build
  script:
    - make